import re
from collections import namedtuple

Token = namedtuple('Token', ['type', 'value', 'line', 'column'])

class LexerError(Exception):
    def __init__(self, message, line, column):
        super().__init__(f"{message} at line {line}, column {column}")
        self.line = line
        self.column = column

class Lexer:
    """A Lexer for the Pascal subset generated by TANGLE."""

    KEYWORDS = {
        'PROGRAM', 'LABEL', 'CONST', 'TYPE', 'VAR', 'PROCEDURE', 'FUNCTION',
        'BEGIN', 'END', 'RECORD', 'IF', 'THEN', 'ELSE', 'WHILE', 'DO',
        'REPEAT', 'UNTIL', 'GOTO', 'CASE', 'OF', 'OTHERWISE', 'EXTERNAL',
        'ARRAY', 'PACKED', 'FILE', 'TEXT', 'FORWARD', 'IN', 'DIV', 'MOD',
        'AND', 'OR', 'NOT'
    }

    TOKEN_SPECIFICATION = [
        ('COMMENT',    r'\{[\s\S]*?\}'),        # Curly brace comments
        ('STRING',     r"'(?:''|[^'])*'"),      # Pascal strings (escaped with '')
        ('HEX',        r'@[0-9A-F]+'),          # Some TANGLE outputs use @ for hex or labels
        ('NUMBER',     r'\d+'),                  # Integer numbers
        ('ASSIGN',     r':='),                   # Assignment operator
        ('RANGE',      r'\.\.'),                 # Range operator
        ('NE',         r'<>'),                   # Not equal
        ('LE',         r'<='),                   # Less than or equal
        ('GE',         r'>='),                   # Greater than or equal
        ('INCLUDE',    r'#include\s+"[^"]+"'),   # C-style includes found in TANGLE output
        ('ID',         r'[a-zA-Z][a-zA-Z0-9_]*'),# Identifiers
        ('OP',         r'[:=<>+\-*/\(\)\[\]\.,;\^]'), # Single-character operators/delimiters
        ('NEWLINE',    r'\n'),                   # Line endings
        ('SKIP',       r'[ \t\r]+'),             # Skip over spaces and tabs
        ('MISMATCH',   r'.'),                    # Any other character
    ]

    def __init__(self, code):
        self.code = code
        self.tokens = []
        self._compile_regex()

    def _compile_regex(self):
        regex_parts = []
        for name, pattern in self.TOKEN_SPECIFICATION:
            regex_parts.append(f'(?P<{name}>{pattern})')
        self.tok_regex = re.compile('|'.join(regex_parts))

    def tokenize(self):
        line_num = 1
        line_start = 0
        for mo in self.tok_regex.finditer(self.code):
            kind = mo.lastgroup
            value = mo.group()
            column = mo.start() - line_start + 1

            if kind == 'NEWLINE':
                line_start = mo.end()
                line_num += 1
                continue
            elif kind == 'SKIP':
                continue
            elif kind == 'MISMATCH':
                raise LexerError(f"Unexpected character {value!r}", line_num, column)

            self.tokens.append(Token(kind, value, line_num, column))

            # Update line and column if the token contains newlines (like COMMENT or STRING)
            if '\n' in value:
                newlines = value.count('\n')
                line_num += newlines
                line_start = mo.start() + value.rfind('\n') + 1

            if kind == 'ID':
                upper_value = value.upper()
                if upper_value in self.KEYWORDS:
                    # Update the last token's type if it's a keyword
                    self.tokens[-1] = self.tokens[-1]._replace(type=upper_value)

        return self.tokens
